package io.github.kdroidfilter.ytdlp.model

import java.time.Duration

/**
 * Represents the metadata for a single video.
 */
data class VideoInfo(
    val id: String,
    val title: String,
    val url: String,
    val thumbnail: String? = null,
    val duration: Duration? = null,
    val description: String? = null,
    val uploader: String? = null,
    val uploaderUrl: String? = null,
    val uploadDate: String? = null, // YYYYMMDD format
    val viewCount: Long? = null,
    val likeCount: Long? = null,
    val width: Int? = null,
    val height: Int? = null,
    val fps: Double? = null,
    val formatNote: String? = null,
    val availableSubtitles: Map<String, SubtitleInfo> = emptyMap(),
    val chapters: List<ChapterInfo> = emptyList(),
    val tags: List<String> = emptyList(),
    val categories: List<String> = emptyList(),
    val directUrl: String? = null,
    val directUrlFormat: String? = null
)

/**
 * Contains information about available subtitles for a specific language.
 */
data class SubtitleInfo(
    val language: String,
    val languageName: String? = null,
    val formats: List<SubtitleFormat> = emptyList(),
    val autoGenerated: Boolean = false
)

/**
 * Represents a specific format (e.g., vtt, srt) of a subtitle file.
 */
data class SubtitleFormat(
    val ext: String,
    val url: String? = null,
    val name: String? = null
)

/**
 * Represents a single chapter within a video.
 */
data class ChapterInfo(
    val title: String? = null,
    val startTime: Double,
    val endTime: Double
)

/**
 * Represents the metadata for a playlist.
 */
data class PlaylistInfo(
    val id: String? = null,
    val title: String? = null,
    val description: String? = null,
    val uploader: String? = null,
    val uploaderUrl: String? = null,
    val entries: List<VideoInfo> = emptyList(),
    val entryCount: Int? = null
)