import io.github.kdroidfilter.ytdlp.YtDlpWrapper
import io.github.kdroidfilter.ytdlp.YtDlpWrapper.InitEvent
import io.github.kdroidfilter.ytdlp.core.Event
import io.github.kdroidfilter.ytdlp.getPlaylistInfo
import io.github.kdroidfilter.ytdlp.getVideoInfo
import kotlinx.coroutines.runBlocking
import java.io.File
import java.time.Duration

fun main() = runBlocking {
    val wrapper = YtDlpWrapper().apply {
        downloadDir = File(System.getProperty("user.home"), "Downloads/yt-dlp")
    }

    // Initialisation
    println("🔧 Initialisation de yt-dlp/ffmpeg…")
    val initOk = wrapper.initialize { ev ->
        when (ev) {
            is InitEvent.CheckingYtDlp -> println("🔍 Vérification de yt-dlp…")
            is InitEvent.DownloadingYtDlp -> println("⬇️ Téléchargement de yt-dlp…")
            is InitEvent.UpdatingYtDlp -> println("⬆️ Mise à jour de yt-dlp…")
            is InitEvent.EnsuringFfmpeg -> println("🎬 Vérification de FFmpeg…")
            is InitEvent.YtDlpProgress -> {
                val pct = ev.percent?.let { String.format("%.1f", it) } ?: "?"
                print("\r⬇️ yt-dlp: $pct%")
            }
            is InitEvent.FfmpegProgress -> {
                val pct = ev.percent?.let { String.format("%.1f", it) } ?: "?"
                print("\r🎬 FFmpeg: $pct%")
            }
            is InitEvent.Error -> {
                println("\n⚠️ Init: ${ev.message}")
                ev.cause?.let { println("   ↳ ${it::class.simpleName}: ${it.message}") }
            }
            is InitEvent.Completed -> println(if (ev.success) "\n✅ Init ok" else "\n❌ Init échouée")
        }
    }

    if (!initOk) {
        println("Arrêt car initialisation impossible.")
        return@runBlocking
    }

    println("✅ yt-dlp version: ${wrapper.version() ?: "inconnue"}")
    println("✅ FFmpeg: ${wrapper.ffmpegPath ?: "(via PATH ou gestion interne)"}")
    println("📁 Download dir: ${wrapper.downloadDir?.absolutePath}")

    // Essayons plusieurs URLs pour tester
    val urls = listOf(
        "https://www.youtube.com/watch?v=0Hv5LTxAutw",
        "https://www.youtube.com/watch?v=UoywDs3YXOM"
    )

    for (url in urls) {
        println("\n🎬 Tentative avec: $url")

        wrapper.getVideoInfo(url, noCheckCertificate = true, timeoutSec = 30)
            .onSuccess { video ->
                println("✅ Succès!")
                println("  📝 Titre: ${video.title}")
                println("  ⏱️ Durée: ${video.duration}")
                println("  🖼️ Thumbnail: ${video.thumbnail}")
                println("  👤 Uploader: ${video.uploader}")
                println("  📅 Date: ${video.uploadDate}")
                println("  👁️ Vues: ${video.viewCount}")

                if (video.availableSubtitles.isNotEmpty()) {
                    println("  📄 Sous-titres disponibles:")
                    video.availableSubtitles.forEach { (lang, info) ->
                        println("    - $lang: ${info.languageName ?: lang} ${if (info.autoGenerated) "(auto)" else ""}")
                    }
                }
            }
            .onFailure { error ->
                println("❌ Échec: ${error.message}")
                error.printStackTrace()

                // Essayons de lancer yt-dlp directement pour voir le problème
                println("\n🔍 Test direct de yt-dlp avec l'URL:")
                try {
                    val testCmd = listOf(
                        wrapper.ytDlpPath,
                        "--dump-json",
                        "--no-playlist",
                        "--no-check-certificate",
                        url
                    )
                    println("  Commande: ${testCmd.joinToString(" ")}")

                    val process = ProcessBuilder(testCmd)
                        .redirectErrorStream(false)
                        .start()

                    val stdout = process.inputStream.bufferedReader().readText()
                    val stderr = process.errorStream.bufferedReader().readText()
                    val exitCode = process.waitFor()

                    println("  Exit code: $exitCode")
                    if (stderr.isNotBlank()) {
                        println("  Stderr (erreurs):")
                        stderr.lines().take(20).forEach { println("    $it") }
                    }
                    if (stdout.isNotBlank()) {
                        println("  Stdout (tronqué à 500 chars):")
                        println("    ${stdout.take(500)}")
                    }
                } catch (e: Exception) {
                    println("  Erreur lors du test direct: ${e.message}")
                }
            }
    }

    wrapper.getPlaylistInfo(
        url = "https://www.youtube.com/watch?v=TmpCU_7hP_s&list=PLQkwcJG4YTCQ3V9U0aJOfhgjeKVuznat0",
        noCheckCertificate = true
    ).onSuccess {
        println(it.title)
    }.onFailure {
        println(it.message)
    }

    // Test de la connectivité réseau vers YouTube
    println("\n🌐 Test de connectivité réseau:")
    wrapper.checkNetwork("https://www.youtube.com", 5000, 5000)
        .onSuccess { println("  ✅ Connexion à YouTube OK") }
        .onFailure { println("  ❌ Problème réseau: ${it.message}") }
}